export { EditProposalsProvider, useEditProposals } from './useEditProposals'
export type { EditProposalsContextValue } from './useEditProposals'
export { default as AdminEditOverlay } from './AdminEditOverlay'
export { default as FloatingEditButton } from './FloatingEditButton'
export { default as ProposalDialog } from './ProposalDialog'
export { default as ProposalCornerButton } from './ProposalCornerButton'
export type { EditProposal, ElementCapture, CaptureType, AnchorRect } from './types'
